"""
Project NOVA - Centralized Subsystem Configuration
Consolidates operational constants, timeouts, and thresholds across subsystems (F-37).
"""

# Audio Subsystem Configuration (NFR-001, FR-001)
DEFAULT_SAMPLE_RATE_HZ = 16000
DEFAULT_BLOCK_SIZE_SAMPLES = 1600
AUDIO_QUEUE_MAXSIZE = 50

# Speech Recognition & Kaldi Configuration (FR-002, FR-003)
DEFAULT_CONFIDENCE_THRESHOLD = 0.65
DEFAULT_SPEECH_DEBOUNCE_SECONDS = 0.25

# Dictation Pipeline Configuration (FR-020, FR-021)
DEFAULT_DICTATION_SILENCE_TIMEOUT_S = 3.0
DEFAULT_DICTATION_GRACE_PERIOD_S = 1.5

# UI & Interaction Defaults (FR-006, FR-015, FR-018, FR-019)
DEFAULT_PAGE_SIZE = 9
DEFAULT_CROSSHAIR_SWEEP_SPEED_PX_S = 180.0
DEFAULT_NUDGE_STEP_PX = 65
DEFAULT_MICRO_NUDGE_STEP_PX = 18
DEFAULT_JUMP_NUDGE_STEP_PX = 160
DEFAULT_SNAP_GRAVITY_RADIUS_PX = 65

# DSP & Acoustic Detection Thresholds (FR-013, FR-014, FR-016)
DEFAULT_SNR_THRESHOLD_DB = 18.0
DEFAULT_MAX_IMPULSE_DURATION_MS = 25.0
DEFAULT_PITCH_CORRELATION_THRESHOLD = 0.65
